########################
# Clean up this file
########################

r2dbc:
  datasources:
    source:
      url: r2dbc:pool:postgresql://source-db:5432/db
      username: user
      password: password
      options: {}
    target:
      url: r2dbc:pool:postgresql://target-db:5432/db
      username: user
      password: password
      options: {}
reconciliation:
  datasets:
    pets:
      source:
        datasourceRef: source
        query: >
          SELECT pet.id AS MigrationKey, category, name, status
          FROM pet
      target:
        datasourceRef: target
        queryFile: examples/scenario/petshop-mariadb/queries/petshop-mariadb-pets-target.sql
