########################
# Clean up this file
########################

r2dbc:
  datasources:
    source:
      url: r2dbc:pool:postgresql://source-db:5432/db
      username: user
      password: password
      options: {}
    target:
      url: r2dbc:pool:postgresql://target-db:5432/db
      username: user
      password: password
      options: {}
reconciliation:
  datasets:
    order_status_count:
      source:
        datasourceRef: source
        queryFile: examples/scenario/petshop-postgres/queries/petshop-postgres-pets-source.sql
      target:
        datasourceRef: target
        queryFile: examples/scenario/petshop-postgres/queries/petshop-postgres-pets-target.sql
