r2dbc:
  datasources:
    source:
      url: r2dbc:pool:mariadb://host.docker.internal:8000/db
      username: user
      password: password
      options: {}
    target:
      url: r2dbc:pool:mariadb://target-db:3306/db
      username: user
      password: password
      options: {}
    default:
      url: r2dbc:pool:postgresql://host.docker.internal:9000/db
      username: user
      password: password
reconciliation:
  datasets:
    petstatus:
      source:
        datasourceRef: source
        query: >
          SELECT status as MigrationKey, COUNT(status) FROM pet GROUP BY status
      target:
        datasourceRef: target
        query: >
          SELECT status_name AS MigrationKey, p.count FROM pet_count_by_status as p
